routes/admin.php
<?php

use Illuminate\Http\Request;
Route::resource('hospitals', 'HospitalController');
Route::get('hospitals/{hospital}/doctors','HospitalController@doctors')->name('hospitals.doctors.list');
Route::put('hospitals/{hospital}/doctors','HospitalController@syncDoctors')->name('hospitals.doctors.sync');
Route::resource('doctors', 'DoctorController');
Route::resource('patients', 'PatientController');

routes/web.php
<?php

Route::get('/', "WebController@index")->name('index');
Route::POST('/hospital', "WebController@hospital")->name('hospital');
Route::POST('/doctor', "WebController@doctor")->name('doctor');

app/Models/Hospital.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Hospital
 *
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Doctor[] $doctors
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\WorkingPeriod[] $working_periods
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Hospital newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Hospital newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Hospital query()
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property string $address
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string|null $deleted_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Hospital whereAddress($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Hospital whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Hospital whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Hospital whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Hospital whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Hospital whereUpdatedAt($value)
 */
class Hospital extends Model
{
    protected $table = 'hospitals';

    protected $guarded = [];

    protected $hidden = [];

    public function doctors()
    {
        return $this->belongsToMany(Doctor::class,'doctor_hospital');
    }

    public function working_periods()
    {
        return $this->hasMany(WorkingPeriod::class);
    }
}

app/Models/Traits/Named.php
<?php


namespace App\Models\Traits;


trait Named
{
    public function getFullNameAttribute()
    {

        return implode(' ', array_filter([
            $this->last_name,
            $this->first_name,
            $this->middle_name]));
    }

    public function getDisplayNameAttribute()
    {
        if (!empty($this->first_name))
            $first = mb_strtoupper(mb_substr($this->first_name,0,1)) . '.';

        if (!empty($this->middle_name))
            $middle = mb_strtoupper(mb_substr($this->middle_name,0,1)). '.';
        return implode(' ', array_filter([
            $this->last_name,
            $first,
            $middle
        ]));
    }
}

app/Http/Controllers/Admin/HospitalController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\HospitalStoreRequest;
use App\Http\Requests\SyncHospitalDoctorsRequest;
use App\Models\Doctor;
use App\Models\Hospital;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class HospitalController extends AdminController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $hospitals = Hospital::all();
        $title = "Список поликлиник";
        return view('admin.hospitals.index', compact('hospitals', 'title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $title = "Добавить новую поликлинику";
        return view('admin.hospitals.create', compact('title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param HospitalStoreRequest $request
     * @return Response
     */
    public function store(HospitalStoreRequest $request)
    {
        $hospital = Hospital::create($request->all());
        return redirect()->route('admin.hospitals.show', $hospital);
    }

    /**
     * Display the specified resource.
     *
     * @param Hospital $hospital
     * @return Response
     */
    public function show(Hospital $hospital)
    {
        $title = $hospital->name;
        return view('admin.hospitals.show', compact('hospital', 'title'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Hospital $hospital
     * @return Response
     */
    public function edit(Hospital $hospital)
    {
        $title = $hospital->name;
        return view('admin.hospitals.edit', compact('hospital', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param HospitalStoreRequest $request
     * @param Hospital $hospital
     * @return Response
     */
    public function update(HospitalStoreRequest $request, Hospital $hospital)
    {
        $hospital->update($request->all());
        return redirect()->route('admin.hospitals.show', $hospital);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Hospital $hospital
     * @return Response
     * @throws Exception
     */
    public function destroy(Hospital $hospital)
    {
        $hospital->delete();
        return redirect()->route('admin.hospitals.index');
    }

    public function doctors(Hospital $hospital)
    {
        $hospital->load('doctors');
        $doctors = Doctor::get()->map(function ($doctor) use ($hospital) {
            $doctor->in_hospital = $hospital->doctors->contains('id', $doctor->id);
            return $doctor;
        });

        return view('admin.hospitals.edit_doctorlist', compact('hospital', 'doctors'));
    }

    public function syncDoctors(SyncHospitalDoctorsRequest $request, Hospital $hospital)
    {
        $hospital->doctors()->sync($request->input('doctors'));
        return redirect()->route('admin.hospitals.show',$hospital);
    }
}

resources/views/admin/hospitals/create.blade.php
@extends('admin.layout.page')

@section('main')
    <div class="container justify-content-center">
        <div class="card p-2">
            <form action="{{route('admin.hospitals.store')}}" method="post">
                @csrf()
                @method('POST')
                <div class="form-group">
                    <label for="name">Название</label>
                    <input type="text" class="@error('name') is-invalid @enderror form-control" id="name" placeholder="Больница им. Святого Гиппократа"
                           name="name"
                           value="{{old('name')}}">
                    @error('name')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="address">Адрес</label>
                    <input type="text" class="form-control" id="address" placeholder="Невский пр-кт, д 1"
                           name="address"
                           value="{{old('address')}}">
                    @error('address')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/hospitals/edit.blade.php
@extends('admin.layout.page')

@section('main')
    <div class="container justify-content-center">
        <div class="card p-2">
            <form action="{{route('admin.hospitals.update', $hospital)}}" method="post">
                @csrf()
                @method('PUT')
                <div class="form-group">
                    <label for="name">Название</label>
                    <input type="text" class="@error('name') is-invalid @enderror form-control" id="name" placeholder="Больница им. Святого Гиппократа"
                           name="name"
                           required value="{{$hospital->name}}">
                    @error('name')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="address">Адрес</label>
                    <input type="text" class="@error('address') is-invalid @enderror form-control" id="address" placeholder="Невский пр-кт, д 1" required
                           name="address"
                           value="{{$hospital->address}}">
                    @error('address')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
            <form action="{{route('admin.hospitals.destroy',$hospital)}}" method="post">
                @csrf()
                @method('DELETE')
                <button type="submit"  class="btn btn-outline-danger mt-3">Удалить</button></form>
        </div>
    </div>
@endsection

resources/views/admin/hospitals/edit_doctorlist.blade.php
@extends('admin.layout.page')

@section('main')
    <div class="container justify-content-center">
        <div class="card p-2">
            <h2>Список врачей в {{$hospital->name}}</h2>
            <form action="{{route('admin.hospitals.doctors.sync', $hospital)}}" method="post">
                @csrf()
                @method('PUT')
                @foreach($doctors as $doctor)
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="doctor-{{$doctor->id}}"
                               name="doctors[]" value="{{$doctor->id}}"
                               @if ($doctor->in_hospital) checked @endif>
                        <label class="custom-control-label" for="doctor-{{$doctor->id}}">{{$doctor->full_name}}</label>
                    </div>
                @endforeach
                <button type="submit" class="btn btn-success mt-2">Сохранить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/hospitals/index.blade.php
@extends('admin.layout.page')

@section('main')
    <div class="container justify-content-center">
        <a href="{{route('admin.hospitals.create')}}" class="d-block my-2">Добавить поликлинику</a>
        <table class="table table-sm table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Название</th>
                <th>Адрес</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach($hospitals as $patient)
                <tr >
                    <td>{{$patient->id}}</td>
                    <td><a href="{{route('admin.hospitals.show',$patient)}}">{{$patient->name}}</a></td>
                    <td>{{$patient->address}}</td>
                    <td><form action="{{route('admin.hospitals.destroy',$patient)}}" method="post">
                            @csrf()
                            @method('DELETE')
                            <button type="submit"  class="btn btn-sm btn-outline-danger">Удалить</button></form></td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/hospitals/show.blade.php
@extends('admin.layout.page')
@section('main')
    <div class="card-columns">
        <div class="card p-2">
            <ul class="list-unstyled">
                <li><b>Название</b>: {{$hospital->name}}</li>
                <li><b>Адрес</b>: {{$hospital->address}}</li>
            </ul>
            <a href="{{route('admin.hospitals.edit',$hospital)}}">Редактировать</a>
        </div>
        <div class="card p-3">
            <h3>Приписанные врачи</h3>
            <a href="{{route('admin.hospitals.doctors.list',$hospital)}}">Редактировать список</a>
            <ul>
                @foreach($hospital->doctors as $doctor)
                <li><a href="{{route('admin.doctors.show',$doctor)}}">{{$doctor->full_name}}</a></li>
                @endforeach
            </ul>
        </div>
    </div>
@endsection