routes/admin.php
<?php

use Illuminate\Http\Request;
Route::resource('hospitals', 'HospitalController');
Route::get('hospitals/{hospital}/doctors','HospitalController@doctors')->name('hospitals.doctors.list');
Route::put('hospitals/{hospital}/doctors','HospitalController@syncDoctors')->name('hospitals.doctors.sync');
Route::resource('doctors', 'DoctorController');
Route::resource('patients', 'PatientController');

routes/web.php
<?php

Route::get('/', "WebController@index")->name('index');
Route::POST('/hospital', "WebController@hospital")->name('hospital');
Route::POST('/doctor', "WebController@doctor")->name('doctor');

app/Models/Doctor.php
<?php

namespace App\Models;

use App\Models\Traits\Named;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Doctor
 *
 * @property-read mixed $display_name
 * @property-read mixed $full_name
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Hospital[] $hospitals
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\WorkingPeriod[] $working_periods
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Doctor newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Doctor newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Doctor query()
 * @mixin \Eloquent
 * @property int $id
 * @property string $first_name
 * @property string $middle_name
 * @property string $last_name
 * @property string $specialization
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string|null $deleted_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Doctor whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Doctor whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Doctor whereFirstName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Doctor whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Doctor whereLastName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Doctor whereMiddleName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Doctor whereSpecialization($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Doctor whereUpdatedAt($value)
 */
class Doctor extends Model
{
    use Named;

    protected $table = 'doctors';

    protected $guarded = [];

    protected $hidden = [];

    public function hospitals()
    {
        return $this->belongsToMany(Hospital::class, 'doctor_hospital');
    }

    public function working_periods()
    {
        return $this->hasMany(WorkingPeriod::class)->orderBy('hospital_id')->orderBy('date');
    }


}

app/Models/Traits/Named.php
<?php


namespace App\Models\Traits;


trait Named
{
    public function getFullNameAttribute()
    {

        return implode(' ', array_filter([
            $this->last_name,
            $this->first_name,
            $this->middle_name]));
    }

    public function getDisplayNameAttribute()
    {
        if (!empty($this->first_name))
            $first = mb_strtoupper(mb_substr($this->first_name,0,1)) . '.';

        if (!empty($this->middle_name))
            $middle = mb_strtoupper(mb_substr($this->middle_name,0,1)). '.';
        return implode(' ', array_filter([
            $this->last_name,
            $first,
            $middle
        ]));
    }
}

app/Http/Controllers/Admin/DoctorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\DoctorStoreRequest;
use App\Models\Doctor;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class DoctorController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $doctors = Doctor::paginate();
        $title = "Список врачей";
        return view('admin.doctors.index', compact('doctors','title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $title = "Добавить врача";
        return view('admin.doctors.create', compact('title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param DoctorStoreRequest $request
     * @return Response
     */
    public function store(DoctorStoreRequest $request)
    {
        $doctor = Doctor::create($request->all());
        return redirect()->route('admin.doctors.show', $doctor);
    }

    /**
     * Display the specified resource.
     *
     * @param Doctor $doctor
     * @return Response
     */
    public function show(Doctor $doctor)
    {
        $title = $doctor->display_name;
        $periods_by_hospitals = $doctor->working_periods->groupBy('hospital_id');
        return view('admin.doctors.show', compact('doctor', 'title', 'periods_by_hospitals'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Doctor $doctor
     * @return Response
     */
    public function edit(Doctor $doctor)
    {
        $title = $doctor->display_name;
        return view('admin.doctors.edit', compact('doctor', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param DoctorStoreRequest $request
     * @param Doctor $doctor
     * @return Response
     */
    public function update(DoctorStoreRequest $request, Doctor $doctor)
    {
        $doctor->update($request->all());
        return redirect()->route('admin.doctors.show', $doctor);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Doctor $doctor
     * @return Response
     * @throws Exception
     */
    public function destroy(Doctor $doctor)
    {
        $doctor->delete();
        return redirect()->route('admin.doctors.index');
    }
}

resources/views/admin/doctors/create.blade.php
@extends('admin.layout.page')

@section('main')
    <div class="container justify-content-center">
        <div class="card p-2">
            <form action="{{route('admin.doctors.store')}}" method="post">
                @csrf()
                @method('POST')
                <div class="form-group">
                    <label for="last_name">Фамилия</label>
                    <input type="text" class="@error('last_name') is-invalid @enderror form-control"
                           id="last_name"
                           name="last_name"
                           value="{{old('last_name')}}">
                    @error('last_name')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="first_name">Имя</label>
                    <input type="text" class="@error('first_name') is-invalid @enderror form-control"
                           id="first_name"
                           name="first_name"
                           value="{{old('first_name')}}">
                    @error('first_name')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="middle_name">Отчество</label>
                    <input type="text" class="@error('middle_name') is-invalid @enderror form-control"
                           id="middle_name"
                           name="middle_name"
                           value="{{old('middle_name')}}">
                    @error('middle_name')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="specialization">Специализация</label>
                    <input type="text" class="@error('specialization') is-invalid @enderror form-control"
                           id="specialization"
                           name="specialization"
                           value="{{old('specialization')}}">
                    @error('specialization')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/doctors/edit.blade.php
@extends('admin.layout.page')

@section('main')
    <div class="container justify-content-center">
        <div class="card p-2">
            <form action="{{route('admin.doctors.update', $doctor)}}" method="post">
                @csrf()
                @method('PUT')
                <div class="form-group">
                    <label for="last_name">Фамилия</label>
                    <input type="text" class="@error('last_name') is-invalid @enderror form-control"
                           id="last_name"
                           name="last_name"
                           value="{{ $doctor->last_name}}">
                    @error('last_name')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="first_name">Имя</label>
                    <input type="text" class="@error('first_name') is-invalid @enderror form-control"
                           id="first_name"
                           name="first_name"
                           value="{{$doctor->first_name}}">
                    @error('first_name')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="middle_name">Отчество</label>
                    <input type="text" class="@error('middle_name') is-invalid @enderror form-control"
                           id="middle_name"
                           name="middle_name"
                           value="{{$doctor->middle_name}}">
                    @error('middle_name')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="specialization">Специализация</label>
                    <input type="text" class="@error('specialization') is-invalid @enderror form-control"
                           id="specialization"
                           name="specialization"
                           value="{{$doctor->specialization}}">
                    @error('specialization')
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/doctors/index.blade.php
@extends('admin.layout.page')

@section('main')
    <div class="container justify-content-center">
        <a href="{{route('admin.doctors.create')}}" class="d-block my-2">Добавить врача</a>
        <table class="table table-sm table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Специализация</th>
                <th>Расписание</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach($doctors as $doctor)
                <tr >
                    <td>{{$doctor->id}}</td>
                    <td><a href="{{route('admin.doctors.show',$doctor)}}">{{$doctor->full_name}}</a></td>
                    <td>{{$doctor->specialization}}</td>
                    <td></td>
                    <td><form action="{{route('admin.doctors.destroy',$doctor)}}" method="post">
                            @csrf()
                            @method('DELETE')
                            <button type="submit"  class="btn btn-sm btn-outline-danger">Удалить</button></form></td>
                </tr>
            @endforeach
            </tbody>
            <caption>
                {{$doctors->links()}}
            </caption>
        </table>

    </div>
@endsection

resources/views/admin/doctors/show.blade.php
@extends('admin.layout.page')
@section('main')
    <div class="card-deck">
        <div class="card p-2">
            <ul class="list-unstyled">
                <li><b>Фамилия</b>: {{$doctor->last_name}}</li>
                <li><b>Имя</b>: {{$doctor->first_name}}</li>
                <li><b>Отчество</b>: {{$doctor->middle_name}}</li>
                <li><b>Специализация</b>: {{$doctor->specialization}}</li>
            </ul>
            <a href="{{route('admin.doctors.edit',$doctor)}}">Редактировать</a>
        </div>
        <div class="card p-3">
            <h3>Поликлиники</h3>
            <ul>
                @foreach($doctor->hospitals as $hospital)
                    <li><a href="{{route('admin.hospitals.show',$hospital)}}">
                            {{$hospital->name}}</a></li>
                @endforeach
            </ul>
        </div>
        <div class="card p-3">
            <h3>Расписание</h3>
            @foreach($periods_by_hospitals as $working_periods)
            <h4> <a href="{{route('admin.hospitals.show',$working_periods->first()->hospital)}}">
                    {{$working_periods->first()->hospital->name}}</a></h4>
            <table class="table table-sm table-striped">
                <thead>
                <tr>
                    <th>Дата</th>
                    <th>Часы работы</th>
                </tr>
                </thead>
                <tbody>
                @foreach($working_periods as $workingPeriod)
                    <tr>
                        <td>
                           {{$workingPeriod->date->format('j M')}}
                        </td>
                        <td>
                            {{$workingPeriod->start}} - {{$workingPeriod->end}}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            @endforeach

        </div>
    </div>
@endsection