routes/admin.php
<?php

use Illuminate\Http\Request;
Route::resource('hospitals', 'HospitalController');
Route::get('hospitals/{hospital}/doctors','HospitalController@doctors')->name('hospitals.doctors.list');
Route::put('hospitals/{hospital}/doctors','HospitalController@syncDoctors')->name('hospitals.doctors.sync');
Route::resource('doctors', 'DoctorController');
Route::resource('patients', 'PatientController');

routes/web.php
<?php

Route::get('/', "WebController@index")->name('index');
Route::POST('/hospital', "WebController@hospital")->name('hospital');
Route::POST('/doctor', "WebController@doctor")->name('doctor');

app/Models/Patient.php
<?php

namespace App\Models;

use App\Models\Traits\Named;
use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * App\Models\Patient
 *
 * @method static Builder|Patient newModelQuery()
 * @method static Builder|Patient newQuery()
 * @method static Builder|Patient query()
 * @mixin Eloquent
 * @property int $id
 * @property string $first_name
 * @property string $middle_name
 * @property string $last_name
 * @property string $birthday
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @method static Builder|Patient whereBirthday($value)
 * @method static Builder|Patient whereCreatedAt($value)
 * @method static Builder|Patient whereFirstName($value)
 * @method static Builder|Patient whereId($value)
 * @method static Builder|Patient whereLastName($value)
 * @method static Builder|Patient whereMiddleName($value)
 * @method static Builder|Patient whereUpdatedAt($value)
 */
class Patient extends Model
{
    use Named;

    protected $table = 'patients';

    protected $guarded = [];

    protected $hidden = [];
}

app/Models/Traits/Named.php
<?php


namespace App\Models\Traits;


trait Named
{
    public function getFullNameAttribute()
    {

        return implode(' ', array_filter([
            $this->last_name,
            $this->first_name,
            $this->middle_name]));
    }

    public function getDisplayNameAttribute()
    {
        if (!empty($this->first_name))
            $first = mb_strtoupper(mb_substr($this->first_name,0,1)) . '.';

        if (!empty($this->middle_name))
            $middle = mb_strtoupper(mb_substr($this->middle_name,0,1)). '.';
        return implode(' ', array_filter([
            $this->last_name,
            $first,
            $middle
        ]));
    }
}

app/Http/Controllers/Admin/PatientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Patient;
use Exception;
use Illuminate\Http\Response;

class PatientController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $patients = Patient::paginate();
        $title = "Список пациентов";
        return view('admin.patients.index', compact('patients','title'));
    }


    /**
     * Display the specified resource.
     *
     * @param Patient $patient
     * @return Response
     */
    public function show(Patient $patient)
    {
        $title = $patient->display_name;
        return view('admin.patients.show', compact('patient', 'title'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Patient $patient
     * @return Response
     * @throws Exception
     */
    public function destroy(Patient $patient)
    {
        $patient->delete();
        return redirect()->route('admin.doctors.index');
    }
}

resources/views/admin/patients/index.blade.php
@extends('admin.layout.page')

@section('main')
    <div class="container justify-content-center">
        <table class="table table-sm table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Дата рождения</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach($patients as $patient)
                <tr >
                    <td>{{$patient->id}}</td>
                    <td><a href="{{route('admin.patients.show',$patient)}}">{{$patient->full_name}}</a></td>
                    <td>{{$patient->birthday}}</td>
                    <td><form action="{{route('admin.patients.destroy',$patient)}}" method="post">
                            @csrf()
                            @method('DELETE')
                            <button type="submit"  class="btn btn-sm btn-outline-danger">Удалить</button></form></td>
                </tr>
            @endforeach
            </tbody>
            <caption>
                {{$patients->links()}}
            </caption>
        </table>

    </div>
@endsection

resources/views/admin/patients/show.blade.php
@extends('admin.layout.page')
@section('main')
    <div class="card-columns">
        <div class="card p-2">
            <ul class="list-unstyled">
                <li><b>Фамилия</b>: {{$patient->last_name}}</li>
                <li><b>Имя</b>: {{$patient->first_name}}</li>
                <li><b>Отчество</b>: {{$patient->middle_name}}</li>
                <li><b>Дата рождения</b>: {{$patient->birthday}}</li>
            </ul>
            <a href="{{route('admin.patients.edit',$patient)}}">Редактировать</a>
        </div>
        <div class="card p-3">
        </div>
    </div>
@endsection