routes/admin.php
<?php

use Illuminate\Http\Request;
Route::resource('hospitals', 'HospitalController');
Route::get('hospitals/{hospital}/doctors','HospitalController@doctors')->name('hospitals.doctors.list');
Route::put('hospitals/{hospital}/doctors','HospitalController@syncDoctors')->name('hospitals.doctors.sync');
Route::resource('doctors', 'DoctorController');
Route::resource('patients', 'PatientController');

routes/web.php
<?php

Route::get('/', "WebController@index")->name('index');
Route::POST('/hospital', "WebController@hospital")->name('hospital');
Route::POST('/doctor', "WebController@doctor")->name('doctor');

resources/views/admin/layout/header.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'AdminPanel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admin.hospitals.index') }}">Поликлиники</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('admin.doctors.index')}}">Врачи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('admin.patients.index')}}">Пациенты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Расписание</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="#}">{{ __('Login') }}</a>
                    </li>
                @else
                    <li class="nav-item">
                        <a class="nav-link" href="#" role="button">
                            {{ Auth::user()->name }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('web.logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('web.logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/admin/layout/page.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{$title ?? config('app.name')}}</title>

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:400,500,700,400italic|Material+Icons">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">


    <link rel="stylesheet" href="/css/app.css" media="all">

</head>
<body>
@include('admin.layout.header')
<div class="container-fluid">
    @yield('main')
</div>
@include('admin.layout.footer')
</body>
</html>